# Generated by Django 4.1.3 on 2022-11-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Openland', '0002_registration_zip_alter_registration_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='district',
            field=models.CharField(default='', max_length=25, verbose_name='District'),
        ),
    ]
